/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Persistencia.alumnoData;
import dominio.alumno;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nestor Marchizone
 */
public class vista extends javax.swing.JFrame {

    private alumnoData alumnoData = new alumnoData();
    private int idSeleccionado = 0;

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(vista.class.getName());

    public vista() {
        initComponents();
        cargarTabla();
    }

    private alumno leerFormulario() {

        String apellidoNombre = jTApellidoyNombre.getText().trim();
        String dni = jTDni.getText().trim();

        if (apellidoNombre.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingresá apellido y nombre"
            );
            return null;
        }

        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ingresá el DNI"
            );
            return null;
        }

        if (jDateChooser1.getDate() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccioná una fecha de nacimiento"
            );
            return null;
        }

        /*
         * El campo de la pantalla dice:
         * Apellido y Nombre
         *
         * Tomamos la primera palabra como apellido
         * y el resto como nombre.
         */
        String[] partes = apellidoNombre.split("\\s+", 2);

        String apellido = partes[0];
        String nombre = "";

        if (partes.length > 1) {
            nombre = partes[1];
        }

        LocalDate fechaNacimiento =
                new java.sql.Date(
                        jDateChooser1.getDate().getTime()
                ).toLocalDate();

        alumno a = new alumno();

        a.setDni(dni);
        a.setApellido(apellido);
        a.setNombre(nombre);
        a.setFechaNacimiento(fechaNacimiento);
        a.setActivo(jCBActivo.isSelected());

        return a;
    }

    private void cargarTabla() {

        DefaultTableModel modelo =
                (DefaultTableModel) jTAlumno.getModel();

        modelo.setRowCount(0);

        for (alumno a : alumnoData.listarAlumnos()) {

            modelo.addRow(new Object[]{
                a.getIdAlumno(),
                a.getApellido() + " " + a.getNombre(),
                a.getFechaNacimiento(),
                a.isActivo()
            });
        }
    }

    private void limpiarCampos() {

        jTApellidoyNombre.setText("");
        jTDni.setText("");
        jDateChooser1.setDate(null);
        jCBActivo.setSelected(false);

        idSeleccionado = 0;

        jTAlumno.clearSelection();
    }

    private void mostrarAlumno(alumno a) {

        idSeleccionado = a.getIdAlumno();

        jTApellidoyNombre.setText(
                a.getApellido() + " " + a.getNombre()
        );

        jTDni.setText(a.getDni());

        jDateChooser1.setDate(
                java.sql.Date.valueOf(a.getFechaNacimiento())
        );

        jCBActivo.setSelected(a.isActivo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JlApellidoyNombre = new javax.swing.JLabel();
        jTApellidoyNombre = new javax.swing.JTextField();
        jLDNI = new javax.swing.JLabel();
        jTDni = new javax.swing.JTextField();
        jLFechaDeNacimiento = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLEstado = new javax.swing.JLabel();
        jCBActivo = new javax.swing.JCheckBox();
        jBAltaMateria = new javax.swing.JButton();
        jBBajaMateria = new javax.swing.JButton();
        JBModMateria = new javax.swing.JButton();
        JBBuscarMateria = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAlumno = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JlApellidoyNombre.setText("Apellido y Nombre");

        jLDNI.setText("N° Documento");

        jLFechaDeNacimiento.setText("Fecha de Nacimiento");

        jLEstado.setText("Estado");

        jCBActivo.setText("Activo");
        jCBActivo.addActionListener(this::jCBActivoActionPerformed);

        jBAltaMateria.setText("Alta Materia");
        jBAltaMateria.addActionListener(this::jBAltaMateriaActionPerformed);

        jBBajaMateria.setText("Baja Materia");
        jBBajaMateria.addActionListener(this::jBBajaMateriaActionPerformed);

        JBModMateria.setText("Modificar");
        JBModMateria.addActionListener(this::JBModMateriaActionPerformed);

        JBBuscarMateria.setText("Buscar");
        JBBuscarMateria.addActionListener(this::JBBuscarMateriaActionPerformed);

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(this::jBLimpiarActionPerformed);

        jLabel1.setText("Gestion de Alumnos");

        jTAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre y Apellido", "Fecha de Nacimiento", "Activo"
            }
        ));
        jTAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAlumnoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTAlumno);

        jScrollPane3.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBAltaMateria)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLFechaDeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jBBajaMateria)
                                        .addGap(89, 89, 89)
                                        .addComponent(JBModMateria)
                                        .addGap(104, 104, 104)
                                        .addComponent(JBBuscarMateria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBLimpiar)))))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JlApellidoyNombre)
                                .addGap(18, 18, 18)
                                .addComponent(jTApellidoyNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlApellidoyNombre)
                    .addComponent(jTApellidoyNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDNI)
                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFechaDeNacimiento)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstado)
                    .addComponent(jCBActivo))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAltaMateria)
                    .addComponent(jBBajaMateria)
                    .addComponent(JBModMateria)
                    .addComponent(JBBuscarMateria)
                    .addComponent(jBLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBActivoActionPerformed

    private void jBAltaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAltaMateriaActionPerformed
        alumno a = leerFormulario();

    if (a == null) {
        return;
    }

    if (alumnoData.buscarPorDni(a.getDni()) != null) {

        JOptionPane.showMessageDialog(
                this,
                "Ya existe un alumno con ese DNI"
        );

        return;
    }

    alumnoData.guardarAlumno(a);

    cargarTabla();
    limpiarCampos();

    JOptionPane.showMessageDialog(
            this,
            "Alumno guardado correctamente"
    );


    }//GEN-LAST:event_jBAltaMateriaActionPerformed

    private void jBBajaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBajaMateriaActionPerformed
       if (idSeleccionado == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccioná un alumno de la tabla"
        );

        return;
    }

    alumnoData.darDeBaja(idSeleccionado);

    cargarTabla();
    limpiarCampos();

    JOptionPane.showMessageDialog(
            this,
            "Alumno dado de baja"
    );

    }//GEN-LAST:event_jBBajaMateriaActionPerformed

    private void JBModMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModMateriaActionPerformed
       if (idSeleccionado == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccioná un alumno de la tabla"
        );

        return;
    }

    alumno a = leerFormulario();

    if (a == null) {
        return;
    }

    a.setIdAlumno(idSeleccionado);

    alumnoData.modificar(a);

    cargarTabla();
    limpiarCampos();

    JOptionPane.showMessageDialog(
            this,
            "Alumno modificado correctamente"
    );
    }//GEN-LAST:event_JBModMateriaActionPerformed

    private void JBBuscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscarMateriaActionPerformed
       String dni = jTDni.getText().trim();

    if (dni.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Ingresá un DNI"
        );

        return;
    }

    alumno a = alumnoData.buscarPorDni(dni);

    if (a == null) {

        JOptionPane.showMessageDialog(
                this,
                "No se encontró el alumno"
        );

    } else {

        mostrarAlumno(a);
    }
    }//GEN-LAST:event_JBBuscarMateriaActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        jTApellidoyNombre.setText("");
        jTDni.setText("");
        jDateChooser1.setDate(null);
        jCBActivo.setSelected(false);
        idSeleccionado = 0;
        jTAlumno.clearSelection();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jTAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAlumnoMouseClicked
        int fila = jTAlumno.getSelectedRow();

        if (fila == -1) {
            return;
        }

        int id = (int) jTAlumno.getValueAt(fila, 0);

        alumno a = alumnoData.buscarPorId(id);

        if (a != null) {
            mostrarAlumno(a);
        }
    }//GEN-LAST:event_jTAlumnoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {

        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {

            if ("Nimbus".equals(info.getName())) {

                javax.swing.UIManager.setLookAndFeel(
                        info.getClassName()
                );

                break;
            }
        }

    } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex) {

        logger.log(
                java.util.logging.Level.SEVERE,
                null,
                ex
        );
    }

    java.awt.EventQueue.invokeLater(
            () -> new vista().setVisible(true)
    );
}
        /* Create and display the form */
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBuscarMateria;
    private javax.swing.JButton JBModMateria;
    private javax.swing.JLabel JlApellidoyNombre;
    private javax.swing.JButton jBAltaMateria;
    private javax.swing.JButton jBBajaMateria;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JCheckBox jCBActivo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLDNI;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFechaDeNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTAlumno;
    private javax.swing.JTextField jTApellidoyNombre;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
