
package Vista;

import Persistencia.alumnoData;
import dominio.alumno;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class vista extends javax.swing.JFrame {

    private alumnoData alumnoData = new alumnoData();
    private int idSeleccionado = 0;

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(vista.class.getName());

    public vista() {
        initComponents();
        cargarTabla();
    }

    private alumno leerFormulario() {

        String apellido = jTApellido.getText().trim();
        String nombre = jTNombre.getText().trim();
        String dni = jTDni.getText().trim();

        if (apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresá el apellido");
            return null;
        }

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresá el nombre");
            return null;
        }

        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresá el DNI");
            return null;
        }

        if (jDateChooser1.getDate() == null) {
            JOptionPane.showMessageDialog(
                    this, "Seleccioná una fecha de nacimiento"
            );
            return null;
        }

        LocalDate fechaNacimiento = new java.sql.Date(
                jDateChooser1.getDate().getTime()
        ).toLocalDate();

        return new alumno(
                dni,
                nombre,
                apellido,
                fechaNacimiento,
                jCBActivo.isSelected()
        );
    }

    private void cargarTabla() {

        DefaultTableModel modelo =
                (DefaultTableModel) jTAlumno.getModel();

        modelo.setRowCount(0);

        for (alumno a : alumnoData.listarAlumnos()) {

            modelo.addRow(new Object[]{
                a.getIdAlumno(),
                a.getApellido() + " " + a.getNombre(),
                a.getFechaNacimiento(),
                a.isActivo()
            });
        }
    }

    private void limpiarCampos() {
        jTApellido.setText("");
        jTNombre.setText("");
        jTDni.setText("");
        jDateChooser1.setDate(null);
        jCBActivo.setSelected(false);

        idSeleccionado = 0;
        jTAlumno.clearSelection();
    }

    private void mostrarAlumno(alumno a) {
        idSeleccionado = a.getIdAlumno();

        jTApellido.setText(a.getApellido());
        jTNombre.setText(a.getNombre());
        jTDni.setText(a.getDni());

        jDateChooser1.setDate(
                java.sql.Date.valueOf(a.getFechaNacimiento())
        );

        jCBActivo.setSelected(a.isActivo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLTitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        JlApellido = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();
        jLDNI = new javax.swing.JLabel();
        jTDni = new javax.swing.JTextField();
        jLFechaDeNacimiento = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLEstado = new javax.swing.JLabel();
        jCBActivo = new javax.swing.JCheckBox();
        jBAltaMateria = new javax.swing.JButton();
        jBBajaMateria = new javax.swing.JButton();
        JBModMateria = new javax.swing.JButton();
        JBBuscarMateria = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAlumno = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo.setText("Gestion de Alumnos");

        jLNombre.setText("Nombre");

        jTNombre.addActionListener(this::jTNombreActionPerformed);

        JlApellido.setText("Apellido");

        jLDNI.setText("N° Documento");

        jLFechaDeNacimiento.setText("Fecha de Nacimiento");

        jLEstado.setText("Estado");

        jCBActivo.setText("Activo");
        jCBActivo.addActionListener(this::jCBActivoActionPerformed);

        jBAltaMateria.setText("Alta Materia");
        jBAltaMateria.addActionListener(this::jBAltaMateriaActionPerformed);

        jBBajaMateria.setText("Baja Materia");
        jBBajaMateria.addActionListener(this::jBBajaMateriaActionPerformed);

        JBModMateria.setText("Modificar");
        JBModMateria.addActionListener(this::JBModMateriaActionPerformed);

        JBBuscarMateria.setText("Buscar");
        JBBuscarMateria.addActionListener(this::JBBuscarMateriaActionPerformed);

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(this::jBLimpiarActionPerformed);

        jTAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre y Apellido", "Fecha de Nacimiento", "Activo"
            }
        ));
        jTAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAlumnoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTAlumno);

        jScrollPane3.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBAltaMateria)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCBActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(524, 524, 524))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jBBajaMateria)
                                        .addGap(89, 89, 89)
                                        .addComponent(JBModMateria)
                                        .addGap(104, 104, 104)
                                        .addComponent(JBBuscarMateria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBLimpiar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDNI)
                                    .addComponent(JlApellido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(jTNombre, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLFechaDeNacimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLNombre))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLTitulo)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlApellido)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLFechaDeNacimiento)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDNI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBActivo)
                    .addComponent(jLEstado))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAltaMateria)
                    .addComponent(jBBajaMateria)
                    .addComponent(JBModMateria)
                    .addComponent(JBBuscarMateria)
                    .addComponent(jBLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBActivoActionPerformed

    private void jBAltaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAltaMateriaActionPerformed
        alumno a = leerFormulario();

        if (a == null) {
            return;
        }

        if (alumnoData.buscarPorDni(a.getDni()) != null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Ya existe un alumno con ese DNI"
            );

            return;
        }       

        if (alumnoData.guardarAlumno(a)) {
            cargarTabla();
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Alumno guardado correctamente");
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo guardar el alumno. Revisá los datos y la conexión.",
                    "Error al guardar",
                    JOptionPane.ERROR_MESSAGE
            );
        }      
    }//GEN-LAST:event_jBAltaMateriaActionPerformed

    private void jBBajaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBajaMateriaActionPerformed
       if (idSeleccionado == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccioná un alumno de la tabla"
        );

        return;
    }

    alumnoData.darDeBaja(idSeleccionado);
        if (alumnoData.darDeBaja(idSeleccionado)) {
            cargarTabla();
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Alumno dado de baja");
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo dar de baja al alumno. Verificá la conexión "
                    + "y que el alumno exista.",
                    "Error al dar de baja",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jBBajaMateriaActionPerformed

    private void JBModMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModMateriaActionPerformed
       if (idSeleccionado == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccioná un alumno de la tabla"
        );

        return;
    }

    alumno a = leerFormulario();

    if (a == null) {
        return;
    }

    a.setIdAlumno(idSeleccionado);

        if (alumnoData.modificar(a)) {
            cargarTabla();
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Alumno modificado correctamente");
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo modificar el alumno. Verificá que el DNI no esté repetido "
                    + "y que haya conexión con la base de datos.",
                    "Error al modificar",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_JBModMateriaActionPerformed

    private void JBBuscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscarMateriaActionPerformed
       String dni = jTDni.getText().trim();

    if (dni.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Ingresá un DNI"
        );

        return;
    }

    alumno a = alumnoData.buscarPorDni(dni);

    if (a == null) {

        JOptionPane.showMessageDialog(
                this,
                "No se encontró el alumno"
        );

    } else {

        mostrarAlumno(a);
    }
    }//GEN-LAST:event_JBBuscarMateriaActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jTAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAlumnoMouseClicked
        int fila = jTAlumno.getSelectedRow();

        if (fila == -1) {
            return;
        }

        int id = (int) jTAlumno.getValueAt(fila, 0);

        alumno a = alumnoData.buscarPorId(id);

        if (a != null) {
            mostrarAlumno(a);
        }
    }//GEN-LAST:event_jTAlumnoMouseClicked

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {

        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {

            if ("Nimbus".equals(info.getName())) {

                javax.swing.UIManager.setLookAndFeel(
                        info.getClassName()
                );

                break;
            }
        }

    } catch (
            ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex) {

        logger.log(
                java.util.logging.Level.SEVERE,
                null,
                ex
        );
    }

    java.awt.EventQueue.invokeLater(
            () -> new vista().setVisible(true)
    );
}
        /* Create and display the form */
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBuscarMateria;
    private javax.swing.JButton JBModMateria;
    private javax.swing.JLabel JlApellido;
    private javax.swing.JButton jBAltaMateria;
    private javax.swing.JButton jBBajaMateria;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JCheckBox jCBActivo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLDNI;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFechaDeNacimiento;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTAlumno;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
